#!/usr/bin/env python
# -*- coding: utf-8 -*-
import unittest, icecream as ic

from source.Controller import Kosha_Subanta_Krdanta_Tiganta, SyntaxAnalysis
from source.Controller.Transliterate import transliterate_lines, IndianLanguages
from source.Model import AmaraKosha_Database_Queries
import os, sys
sys.path.append(os.getcwd())

class Test(unittest.TestCase):
    def test_morphological_syntactic_analysis_exception_giving_sentences(self):
        sentences = ['कमलानि पश्यति ।', 'रामः पूजयति ।', 'व्याधयः नश्यन्ति ।', 'अरिः पीडयति', 'नृपः जयति ।', 'धनं नश्यति ।', 'वारीणि शुष्यन्ति ।', 'नाविकाः नदेन समुद्रं प्रविशन्ति  ।']
        # outExpected, resultExpected = {}, {}
        for sentence in sentences:
            out, result = self.morphological_syntactic_analysis_exception_givers_print(sentence)
            # outExpected[sentence], resultExpected[sentence] = [AmaraKosha_Database_Queries.iscii_unicode(str(l)) for l in out],\
            #                                                   [AmaraKosha_Database_Queries.iscii_unicode(str(l)) for l in result]
            self.morphological_syntactic_analysis_exception_givers_assert(sentence)
        # print('outExpected = ', outExpected)
        # print('resultExpected = ', resultExpected)

    def morphological_syntactic_analysis_exception_givers_print(self, sentence):
        numpages, subforms, krdforms, tigforms, Subantas, Krdantas, Tigantas = 0, [], [], [], [], [], []
        syntaxInputFile = []
        for i, word in enumerate(sentence.split(' ')):
            word = AmaraKosha_Database_Queries.unicode_iscii(word)
            try:
                wids = 1
                forms, subDetails = Kosha_Subanta_Krdanta_Tiganta.subanta_Analysis(word)
                if not forms == []: subforms += forms
                for item in subDetails:
                    numpages += 1
                    Subantas.append([item.rupam,
                                     transliterate_lines(AmaraKosha_Database_Queries.iscii_unicode(item.base),
                                                         IndianLanguages[0]),
                                     item.anta, item.linga, item.vib, item.vach, item.vibvach])
                    syntaxInputFile.append([i + 1, word, wids, 1, item.base, item.erb, item.det, item.vibvach + 1])
                    wids += 1
            except Exception as e:
                print(e)
            try:
                forms, krdData = Kosha_Subanta_Krdanta_Tiganta.krdanta_Analysis(word)
                if not forms == []: krdforms += forms
                if not krdData == []:
                    Krdantas += krdData
                    numpages += len(krdData)
                    for krdDetail in krdData:
                        syntaxInputFile.append(
                            [i + 1, word, wids, 2, krdDetail.erb_iscii, krdDetail.sabda_iscii, krdDetail.det,
                             krdDetail.vibvach + 1, krdDetail.ddet, krdDetail.Dno, krdDetail.verb_iscii,
                             krdDetail.nijverb_iscii,
                             krdDetail.sanverb_iscii, krdDetail.meaning_iscii, krdDetail.GPICode,
                             krdDetail.CombinedM,
                             krdDetail.karmaCode])
                        wids += 1
            except Exception as e:
                print(e)
            try:
                forms, tigDatas = Kosha_Subanta_Krdanta_Tiganta.tiganta_Analysis(word)
                if not forms == []: tigforms += forms
                if not tigDatas == []:
                    Tigantas += tigDatas
                    numpages += len(tigDatas)
                    for tigData in tigDatas:
                        # ic.ic('tiganta', i+1, word, wids)
                        syntaxInputFile.append(
                            [i + 1, word, wids, 5, tigData.base_iscii, tigData.Dno, tigData.verb_iscii,
                             tigData.nijverb_iscii, tigData.sanverb_iscii, tigData.meaning_iscii, tigData.GPICode,
                             tigData.pralak, tigData.purvach, tigData.CombinedM, tigData.karmaCode])
                        wids += 1
            except Exception as e:
                print(e)
        # ic.ic(numpages, subforms, krdforms, tigforms, Subantas, [item.get() for item in Krdantas], [item.get() for item in Tigantas], syntaxInputFile)

        morphologicalOutput = [AmaraKosha_Database_Queries.unicode_iscii('वाक्यम्') + ' -- %s' % AmaraKosha_Database_Queries.unicode_iscii(sentence)]
        for line in syntaxInputFile:
            morphologicalOutput.append('%d) ' % line[0] + ' '.join([str(x) for x in line[1:]]))
        morphologicalOutput.append('----------')
        try:
            out = SyntaxAnalysis.write_out_aci(morphologicalOutput)
            result = SyntaxAnalysis.write_result_aci(out)
            return out, result
        except Exception as e:
            ic.ic(sentence, e)
    def morphological_syntactic_analysis_exception_givers_assert(self, sentence):
        numpages, subforms, krdforms, tigforms, Subantas, Krdantas, Tigantas = 0, [], [], [], [], [], []
        outExpected = {
            'कमलानि पश्यति ।': ['वाक्यम् -- कमलानि पश्यति   (  1/ 9 )\n', '1) कमलानि 1 1 कमल कमल् a20121 3\n',
                                '2) पश्यति 1 2 पश्य पश्यत् s1032 19 f1 221 दृशिर् दर्शय् दिदृक्षि प्रेक्षण 012 * 0\n',
                                '----------\n', 'वाक्यम् -- कमलानि पश्यति   (  2/ 9 )\n',
                                '1) कमलानि 1 1 कमल कमल् a20121 3\n',
                                '2) पश्यति 2 2 पश्य पश्यत् s2031 19 f1 221 दृशिर् दर्शय् दिदृक्षि प्रेक्षण 012 * 0\n',
                                '----------\n', 'वाक्यम् -- कमलानि पश्यति   (  3/ 9 )\n',
                                '1) कमलानि 1 1 कमल कमल् a20121 3\n',
                                '2) पश्यति 3 5 पश्य् 221 दृशिर् दर्शय् दिदृक्षि प्रेक्षणे1/ 012 1A1 1 * 1\n',
                                '----------\n', 'वाक्यम् -- कमलानि पश्यति   (  4/ 9 )\n',
                                '1) कमलानि 2 1 कमल कमल् a20121 6\n',
                                '2) पश्यति 1 2 पश्य पश्यत् s1032 19 f1 221 दृशिर् दर्शय् दिदृक्षि प्रेक्षण 012 * 0\n',
                                '----------\n', 'वाक्यम् -- कमलानि पश्यति   (  5/ 9 )\n',
                                '1) कमलानि 2 1 कमल कमल् a20121 6\n',
                                '2) पश्यति 2 2 पश्य पश्यत् s2031 19 f1 221 दृशिर् दर्शय् दिदृक्षि प्रेक्षण 012 * 0\n',
                                '----------\n', 'वाक्यम् -- कमलानि पश्यति   (  6/ 9 )\n',
                                '1) कमलानि 2 1 कमल कमल् a20121 6\n',
                                '2) पश्यति 3 5 पश्य् 221 दृशिर् दर्शय् दिदृक्षि प्रेक्षणे1/ 012 1A1 1 * 1\n',
                                '----------\n', 'वाक्यम् -- कमलानि पश्यति   (  7/ 9 )\n',
                                '1) कमलानि 3 1 कमल कमल् a20121 24\n',
                                '2) पश्यति 1 2 पश्य पश्यत् s1032 19 f1 221 दृशिर् दर्शय् दिदृक्षि प्रेक्षण 012 * 0\n',
                                '----------\n', 'वाक्यम् -- कमलानि पश्यति   (  8/ 9 )\n',
                                '1) कमलानि 3 1 कमल कमल् a20121 24\n',
                                '2) पश्यति 2 2 पश्य पश्यत् s2031 19 f1 221 दृशिर् दर्शय् दिदृक्षि प्रेक्षण 012 * 0\n',
                                '----------\n', 'वाक्यम् -- कमलानि पश्यति   (  9/ 9 )\n',
                                '1) कमलानि 3 1 कमल कमल् a20121 24\n',
                                '2) पश्यति 3 5 पश्य् 221 दृशिर् दर्शय् दिदृक्षि प्रेक्षणे1/ 012 1A1 1 * 1\n',
                                '----------\n'],
            'रामः पूजयति ।': ['वाक्यम् -- रामः पूजयति   (  1/ 12 )\n', '1) रामः 1 1 राम राम् a10111 1\n',
                              '2) पूजयति 1 2 पूजय पूजयत् s1032 19 f1 252 पूज् पूजय् पुपूजि पूजायाम 931 * 0\n',
                              '----------\n', 'वाक्यम् -- रामः पूजयति   (  2/ 12 )\n',
                              '1) रामः 1 1 राम राम् a10111 1\n',
                              '2) पूजयति 2 2 पूजय पूजयत् s2031 19 f1 252 पूज् पूजय् पुपूजि पूजायाम 931 * 0\n',
                              '----------\n', 'वाक्यम् -- रामः पूजयति   (  3/ 12 )\n',
                              '1) रामः 1 1 राम राम् a10111 1\n',
                              '2) पूजयति 3 2 पूजय पूजयत् s1032 19 f2 252 पूज् पूजय् पुपूजि पूजायाम 931 * 0\n',
                              '----------\n', 'वाक्यम् -- रामः पूजयति   (  4/ 12 )\n',
                              '1) रामः 1 1 राम राम् a10111 1\n',
                              '2) पूजयति 4 2 पूजय पूजयत् s2031 19 f2 252 पूज् पूजय् पुपूजि पूजायाम 931 * 0\n',
                              '----------\n', 'वाक्यम् -- रामः पूजयति   (  5/ 12 )\n',
                              '1) रामः 1 1 राम राम् a10111 1\n',
                              '2) पूजयति 5 5 पूजय् 252 पूज् पूजय् पुपूजि पूजायाम्1/ 931 1A1 1 * 1\n', '----------\n',
                              'वाक्यम् -- रामः पूजयति   (  6/ 12 )\n', '1) रामः 1 1 राम राम् a10111 1\n',
                              '2) पूजयति 6 5 पूजय् 252 पूज् पूजय् पुपूजि पूजायाम्1/ 931 2A1 1 * 1\n', '----------\n',
                              'वाक्यम् -- रामः पूजयति   (  7/ 12 )\n',
                              '1) रामः 2 5 र् 206 रा रापि रिरास् दाने1/ 112 1A111 9 * 1\n',
                              '2) पूजयति 1 2 पूजय पूजयत् s1032 19 f1 252 पूज् पूजय् पुपूजि पूजायाम 931 * 0\n',
                              '----------\n', 'वाक्यम् -- रामः पूजयति   (  8/ 12 )\n',
                              '1) रामः 2 5 र् 206 रा रापि रिरास् दाने1/ 112 1A111 9 * 1\n',
                              '2) पूजयति 2 2 पूजय पूजयत् s2031 19 f1 252 पूज् पूजय् पुपूजि पूजायाम 931 * 0\n',
                              '----------\n', 'वाक्यम् -- रामः पूजयति   (  9/ 12 )\n',
                              '1) रामः 2 5 र् 206 रा रापि रिरास् दाने1/ 112 1A111 9 * 1\n',
                              '2) पूजयति 3 2 पूजय पूजयत् s1032 19 f2 252 पूज् पूजय् पुपूजि पूजायाम 931 * 0\n',
                              '----------\n', 'वाक्यम् -- रामः पूजयति   (  10/ 12 )\n',
                              '1) रामः 2 5 र् 206 रा रापि रिरास् दाने1/ 112 1A111 9 * 1\n',
                              '2) पूजयति 4 2 पूजय पूजयत् s2031 19 f2 252 पूज् पूजय् पुपूजि पूजायाम 931 * 0\n',
                              '----------\n', 'वाक्यम् -- रामः पूजयति   (  11/ 12 )\n',
                              '1) रामः 2 5 र् 206 रा रापि रिरास् दाने1/ 112 1A111 9 * 1\n',
                              '2) पूजयति 5 5 पूजय् 252 पूज् पूजय् पुपूजि पूजायाम्1/ 931 1A1 1 * 1\n', '----------\n',
                              'वाक्यम् -- रामः पूजयति   (  12/ 12 )\n',
                              '1) रामः 2 5 र् 206 रा रापि रिरास् दाने1/ 112 1A111 9 * 1\n',
                              '2) पूजयति 6 5 पूजय् 252 पूज् पूजय् पुपूजि पूजायाम्1/ 931 2A1 1 * 1\n', '----------\n'],
            'व्याधयः नश्यन्ति ।': ['वाक्यम् -- व्याधयः नश्यन्ति   (  1/ 20 )\n',
                                   '1) व्याधयः 1 1 व्याधि व्याध् c102*1 3\n',
                                   '2) नश्यन्ति 1 2 नश्यन्त् नश्यन्ती d0021 22 f1 23 णश् नाशि निनशिश् अदर्शन 313 * 1\n',
                                   '----------\n', 'वाक्यम् -- व्याधयः नश्यन्ति   (  2/ 20 )\n',
                                   '1) व्याधयः 1 1 व्याधि व्याध् c102*1 3\n',
                                   '2) नश्यन्ति 2 2 नश्य नश्यत् s2031 3 f1 23 णश् नाशि निनशिश् अदर्शन 313 * 1\n',
                                   '----------\n', 'वाक्यम् -- व्याधयः नश्यन्ति   (  3/ 20 )\n',
                                   '1) व्याधयः 1 1 व्याधि व्याध् c102*1 3\n',
                                   '2) नश्यन्ति 3 2 नश्य नश्यत् s2031 6 f1 23 णश् नाशि निनशिश् अदर्शन 313 * 1\n',
                                   '----------\n', 'वाक्यम् -- व्याधयः नश्यन्ति   (  4/ 20 )\n',
                                   '1) व्याधयः 1 1 व्याधि व्याध् c102*1 3\n',
                                   '2) नश्यन्ति 4 2 नश्य नश्यत् s2031 24 f1 23 णश् नाशि निनशिश् अदर्शन 313 * 1\n',
                                   '----------\n', 'वाक्यम् -- व्याधयः नश्यन्ति   (  5/ 20 )\n',
                                   '1) व्याधयः 1 1 व्याधि व्याध् c102*1 3\n',
                                   '2) नश्यन्ति 5 5 नश्य् 23 णश् नाशि निनशिश् अदर्शने2/ 313 1A1 3 * 2\n',
                                   '----------\n', 'वाक्यम् -- व्याधयः नश्यन्ति   (  6/ 20 )\n',
                                   '1) व्याधयः 2 1 व्याधि व्याध् c102*1 24\n',
                                   '2) नश्यन्ति 1 2 नश्यन्त् नश्यन्ती d0021 22 f1 23 णश् नाशि निनशिश् अदर्शन 313 * 1\n',
                                   '----------\n', 'वाक्यम् -- व्याधयः नश्यन्ति   (  7/ 20 )\n',
                                   '1) व्याधयः 2 1 व्याधि व्याध् c102*1 24\n',
                                   '2) नश्यन्ति 2 2 नश्य नश्यत् s2031 3 f1 23 णश् नाशि निनशिश् अदर्शन 313 * 1\n',
                                   '----------\n', 'वाक्यम् -- व्याधयः नश्यन्ति   (  8/ 20 )\n',
                                   '1) व्याधयः 2 1 व्याधि व्याध् c102*1 24\n',
                                   '2) नश्यन्ति 3 2 नश्य नश्यत् s2031 6 f1 23 णश् नाशि निनशिश् अदर्शन 313 * 1\n',
                                   '----------\n', 'वाक्यम् -- व्याधयः नश्यन्ति   (  9/ 20 )\n',
                                   '1) व्याधयः 2 1 व्याधि व्याध् c102*1 24\n',
                                   '2) नश्यन्ति 4 2 नश्य नश्यत् s2031 24 f1 23 णश् नाशि निनशिश् अदर्शन 313 * 1\n',
                                   '----------\n', 'वाक्यम् -- व्याधयः नश्यन्ति   (  10/ 20 )\n',
                                   '1) व्याधयः 2 1 व्याधि व्याध् c102*1 24\n',
                                   '2) नश्यन्ति 5 5 नश्य् 23 णश् नाशि निनशिश् अदर्शने2/ 313 1A1 3 * 2\n',
                                   '----------\n', 'वाक्यम् -- व्याधयः नश्यन्ति   (  11/ 20 )\n',
                                   '1) व्याधयः 3 1 व्याधि व्याध् c001*1 3\n',
                                   '2) नश्यन्ति 1 2 नश्यन्त् नश्यन्ती d0021 22 f1 23 णश् नाशि निनशिश् अदर्शन 313 * 1\n',
                                   '----------\n', 'वाक्यम् -- व्याधयः नश्यन्ति   (  12/ 20 )\n',
                                   '1) व्याधयः 3 1 व्याधि व्याध् c001*1 3\n',
                                   '2) नश्यन्ति 2 2 नश्य नश्यत् s2031 3 f1 23 णश् नाशि निनशिश् अदर्शन 313 * 1\n',
                                   '----------\n', 'वाक्यम् -- व्याधयः नश्यन्ति   (  13/ 20 )\n',
                                   '1) व्याधयः 3 1 व्याधि व्याध् c001*1 3\n',
                                   '2) नश्यन्ति 3 2 नश्य नश्यत् s2031 6 f1 23 णश् नाशि निनशिश् अदर्शन 313 * 1\n',
                                   '----------\n', 'वाक्यम् -- व्याधयः नश्यन्ति   (  14/ 20 )\n',
                                   '1) व्याधयः 3 1 व्याधि व्याध् c001*1 3\n',
                                   '2) नश्यन्ति 4 2 नश्य नश्यत् s2031 24 f1 23 णश् नाशि निनशिश् अदर्शन 313 * 1\n',
                                   '----------\n', 'वाक्यम् -- व्याधयः नश्यन्ति   (  15/ 20 )\n',
                                   '1) व्याधयः 3 1 व्याधि व्याध् c001*1 3\n',
                                   '2) नश्यन्ति 5 5 नश्य् 23 णश् नाशि निनशिश् अदर्शने2/ 313 1A1 3 * 2\n',
                                   '----------\n', 'वाक्यम् -- व्याधयः नश्यन्ति   (  16/ 20 )\n',
                                   '1) व्याधयः 4 1 व्याधि व्याध् c001*1 24\n',
                                   '2) नश्यन्ति 1 2 नश्यन्त् नश्यन्ती d0021 22 f1 23 णश् नाशि निनशिश् अदर्शन 313 * 1\n',
                                   '----------\n', 'वाक्यम् -- व्याधयः नश्यन्ति   (  17/ 20 )\n',
                                   '1) व्याधयः 4 1 व्याधि व्याध् c001*1 24\n',
                                   '2) नश्यन्ति 2 2 नश्य नश्यत् s2031 3 f1 23 णश् नाशि निनशिश् अदर्शन 313 * 1\n',
                                   '----------\n', 'वाक्यम् -- व्याधयः नश्यन्ति   (  18/ 20 )\n',
                                   '1) व्याधयः 4 1 व्याधि व्याध् c001*1 24\n',
                                   '2) नश्यन्ति 3 2 नश्य नश्यत् s2031 6 f1 23 णश् नाशि निनशिश् अदर्शन 313 * 1\n',
                                   '----------\n', 'वाक्यम् -- व्याधयः नश्यन्ति   (  19/ 20 )\n',
                                   '1) व्याधयः 4 1 व्याधि व्याध् c001*1 24\n',
                                   '2) नश्यन्ति 4 2 नश्य नश्यत् s2031 24 f1 23 णश् नाशि निनशिश् अदर्शन 313 * 1\n',
                                   '----------\n', 'वाक्यम् -- व्याधयः नश्यन्ति   (  20/ 20 )\n',
                                   '1) व्याधयः 4 1 व्याधि व्याध् c001*1 24\n',
                                   '2) नश्यन्ति 5 5 नश्य् 23 णश् नाशि निनशिश् अदर्शने2/ 313 1A1 3 * 2\n',
                                   '----------\n'],
            'अरिः पीडयति': ['वाक्यम् -- अरिः पीडयत  (  1/ 6 )\n', '1) अरिः 1 1 अरि अर् c10111 1\n',
                            '2) पीडयति 1 2 पीडय पीडयत् s1032 19 f1 310 पीड् पीडय् पिपीडि गहन 931 * 0\n', '----------\n',
                            'वाक्यम् -- अरिः पीडयत  (  2/ 6 )\n', '1) अरिः 1 1 अरि अर् c10111 1\n',
                            '2) पीडयति 2 2 पीडय पीडयत् s2031 19 f1 310 पीड् पीडय् पिपीडि गहन 931 * 0\n', '----------\n',
                            'वाक्यम् -- अरिः पीडयत  (  3/ 6 )\n', '1) अरिः 1 1 अरि अर् c10111 1\n',
                            '2) पीडयति 3 2 पीडय पीडयत् s1032 19 f2 310 पीड् पीडय् पिपीडि गहन 931 * 0\n', '----------\n',
                            'वाक्यम् -- अरिः पीडयत  (  4/ 6 )\n', '1) अरिः 1 1 अरि अर् c10111 1\n',
                            '2) पीडयति 4 2 पीडय पीडयत् s2031 19 f2 310 पीड् पीडय् पिपीडि गहन 931 * 0\n', '----------\n',
                            'वाक्यम् -- अरिः पीडयत  (  5/ 6 )\n', '1) अरिः 1 1 अरि अर् c10111 1\n',
                            '2) पीडयति 5 5 पीडय् 310 पीड् पीडय् पिपीडि गहने1/ 931 1A1 1 * 1\n', '----------\n',
                            'वाक्यम् -- अरिः पीडयत  (  6/ 6 )\n', '1) अरिः 1 1 अरि अर् c10111 1\n',
                            '2) पीडयति 6 5 पीडय् 310 पीड् पीडय् पिपीडि गहने1/ 931 2A1 1 * 1\n', '----------\n'],
            'नृपः जयति ।': ['वाक्यम् -- नृपः जयति   (  1/ 3 )\n', '1) नृपः 1 1 नृप नृप् a10111 1\n',
                            '2) जयति 1 2 जय जयत् s1032 19 f1 191 जि जापि जिगीषि अबिभव 012 * 0\n', '----------\n',
                            'वाक्यम् -- नृपः जयति   (  2/ 3 )\n', '1) नृपः 1 1 नृप नृप् a10111 1\n',
                            '2) जयति 2 2 जय जयत् s2031 19 f1 191 जि जापि जिगीषि अबिभव 012 * 0\n', '----------\n',
                            'वाक्यम् -- नृपः जयति   (  3/ 3 )\n', '1) नृपः 1 1 नृप नृप् a10111 1\n',
                            '2) जयति 3 5 जय् 191 जि जापि जिगीषि अबिभवे1/ 012 1A1 1 * 1\n', '----------\n'],
            'धनं नश्यति ।': ['वाक्यम् -- धनं नश्यति   (  1/ 6 )\n', '1) धनं 1 1 धन धन् a20121 1\n',
                             '2) नश्यति 1 2 नश्य नश्यत् s1011 19 f1 23 णश् नाशि निनशिश् अदर्शन 313 * 1\n',
                             '----------\n', 'वाक्यम् -- धनं नश्यति   (  2/ 6 )\n', '1) धनं 1 1 धन धन् a20121 1\n',
                             '2) नश्यति 2 2 नश्य नश्यत् s2031 19 f1 23 णश् नाशि निनशिश् अदर्शन 313 * 1\n',
                             '----------\n', 'वाक्यम् -- धनं नश्यति   (  3/ 6 )\n', '1) धनं 1 1 धन धन् a20121 1\n',
                             '2) नश्यति 3 5 नश्य् 23 णश् नाशि निनशिश् अदर्शने2/ 313 1A1 1 * 2\n', '----------\n',
                             'वाक्यम् -- धनं नश्यति   (  4/ 6 )\n', '1) धनं 2 1 धन धन् a20121 4\n',
                             '2) नश्यति 1 2 नश्य नश्यत् s1011 19 f1 23 णश् नाशि निनशिश् अदर्शन 313 * 1\n',
                             '----------\n', 'वाक्यम् -- धनं नश्यति   (  5/ 6 )\n', '1) धनं 2 1 धन धन् a20121 4\n',
                             '2) नश्यति 2 2 नश्य नश्यत् s2031 19 f1 23 णश् नाशि निनशिश् अदर्शन 313 * 1\n',
                             '----------\n', 'वाक्यम् -- धनं नश्यति   (  6/ 6 )\n', '1) धनं 2 1 धन धन् a20121 4\n',
                             '2) नश्यति 3 5 नश्य् 23 णश् नाशि निनशिश् अदर्शने2/ 313 1A1 1 * 2\n', '----------\n'],
            'वारीणि शुष्यन्ति ।': ['वाक्यम् -- वारीणि शुष्यन्ति   (  1/ 15 )\n', '1) वारीणि 1 1 वारि वार् c20121 3\n',
                                   '2) शुष्यन्ति 1 2 शुष्यन्त् शुष्यन्ती d0021 22 f1 332 शुष् शोषय् शुशुक्षि शोषण 312 * 0\n',
                                   '----------\n', 'वाक्यम् -- वारीणि शुष्यन्ति   (  2/ 15 )\n',
                                   '1) वारीणि 1 1 वारि वार् c20121 3\n',
                                   '2) शुष्यन्ति 2 2 शुष्य शुष्यत् s2031 3 f1 332 शुष् शोषय् शुशुक्षि शोषण 312 * 0\n',
                                   '----------\n', 'वाक्यम् -- वारीणि शुष्यन्ति   (  3/ 15 )\n',
                                   '1) वारीणि 1 1 वारि वार् c20121 3\n',
                                   '2) शुष्यन्ति 3 2 शुष्य शुष्यत् s2031 6 f1 332 शुष् शोषय् शुशुक्षि शोषण 312 * 0\n',
                                   '----------\n', 'वाक्यम् -- वारीणि शुष्यन्ति   (  4/ 15 )\n',
                                   '1) वारीणि 1 1 वारि वार् c20121 3\n',
                                   '2) शुष्यन्ति 4 2 शुष्य शुष्यत् s2031 24 f1 332 शुष् शोषय् शुशुक्षि शोषण 312 * 0\n',
                                   '----------\n', 'वाक्यम् -- वारीणि शुष्यन्ति   (  5/ 15 )\n',
                                   '1) वारीणि 1 1 वारि वार् c20121 3\n',
                                   '2) शुष्यन्ति 5 5 शुष्य् 332 शुष् शोषय् शुशुक्षि शोषणे1/ 312 1A1 3 * 1\n',
                                   '----------\n', 'वाक्यम् -- वारीणि शुष्यन्ति   (  6/ 15 )\n',
                                   '1) वारीणि 2 1 वारि वार् c20121 6\n',
                                   '2) शुष्यन्ति 1 2 शुष्यन्त् शुष्यन्ती d0021 22 f1 332 शुष् शोषय् शुशुक्षि शोषण 312 * 0\n',
                                   '----------\n', 'वाक्यम् -- वारीणि शुष्यन्ति   (  7/ 15 )\n',
                                   '1) वारीणि 2 1 वारि वार् c20121 6\n',
                                   '2) शुष्यन्ति 2 2 शुष्य शुष्यत् s2031 3 f1 332 शुष् शोषय् शुशुक्षि शोषण 312 * 0\n',
                                   '----------\n', 'वाक्यम् -- वारीणि शुष्यन्ति   (  8/ 15 )\n',
                                   '1) वारीणि 2 1 वारि वार् c20121 6\n',
                                   '2) शुष्यन्ति 3 2 शुष्य शुष्यत् s2031 6 f1 332 शुष् शोषय् शुशुक्षि शोषण 312 * 0\n',
                                   '----------\n', 'वाक्यम् -- वारीणि शुष्यन्ति   (  9/ 15 )\n',
                                   '1) वारीणि 2 1 वारि वार् c20121 6\n',
                                   '2) शुष्यन्ति 4 2 शुष्य शुष्यत् s2031 24 f1 332 शुष् शोषय् शुशुक्षि शोषण 312 * 0\n',
                                   '----------\n', 'वाक्यम् -- वारीणि शुष्यन्ति   (  10/ 15 )\n',
                                   '1) वारीणि 2 1 वारि वार् c20121 6\n',
                                   '2) शुष्यन्ति 5 5 शुष्य् 332 शुष् शोषय् शुशुक्षि शोषणे1/ 312 1A1 3 * 1\n',
                                   '----------\n', 'वाक्यम् -- वारीणि शुष्यन्ति   (  11/ 15 )\n',
                                   '1) वारीणि 3 1 वारि वार् c20121 24\n',
                                   '2) शुष्यन्ति 1 2 शुष्यन्त् शुष्यन्ती d0021 22 f1 332 शुष् शोषय् शुशुक्षि शोषण 312 * 0\n',
                                   '----------\n', 'वाक्यम् -- वारीणि शुष्यन्ति   (  12/ 15 )\n',
                                   '1) वारीणि 3 1 वारि वार् c20121 24\n',
                                   '2) शुष्यन्ति 2 2 शुष्य शुष्यत् s2031 3 f1 332 शुष् शोषय् शुशुक्षि शोषण 312 * 0\n',
                                   '----------\n', 'वाक्यम् -- वारीणि शुष्यन्ति   (  13/ 15 )\n',
                                   '1) वारीणि 3 1 वारि वार् c20121 24\n',
                                   '2) शुष्यन्ति 3 2 शुष्य शुष्यत् s2031 6 f1 332 शुष् शोषय् शुशुक्षि शोषण 312 * 0\n',
                                   '----------\n', 'वाक्यम् -- वारीणि शुष्यन्ति   (  14/ 15 )\n',
                                   '1) वारीणि 3 1 वारि वार् c20121 24\n',
                                   '2) शुष्यन्ति 4 2 शुष्य शुष्यत् s2031 24 f1 332 शुष् शोषय् शुशुक्षि शोषण 312 * 0\n',
                                   '----------\n', 'वाक्यम् -- वारीणि शुष्यन्ति   (  15/ 15 )\n',
                                   '1) वारीणि 3 1 वारि वार् c20121 24\n',
                                   '2) शुष्यन्ति 5 5 शुष्य् 332 शुष् शोषय् शुशुक्षि शोषणे1/ 312 1A1 3 * 1\n',
                                   '----------\n'],
            'नाविकाः नदेन समुद्रं प्रविशन्ति  ।': ['वाक्यम् -- नाविकाः नदेन समुद्रं प्रविशन्ति    (  1/ 2 )\n',
                                                   '1) नाविकाः 1 1 नाविक नाविक् a10211 3\n',
                                                   '2) नदेन 1 1 नद नद् a102*1 7\n',
                                                   '3) समुद्रं 1 1 समुद्र समुद्र् a101*1 4\n', '----------\n',
                                                   'वाक्यम् -- नाविकाः नदेन समुद्रं प्रविशन्ति    (  2/ 2 )\n',
                                                   '1) नाविकाः 2 1 नाविक नाविक् a10211 24\n',
                                                   '2) नदेन 1 1 नद नद् a102*1 7\n',
                                                   '3) समुद्रं 1 1 समुद्र समुद्र् a101*1 4\n', '----------\n']}
        resultExpected = {
            'कमलानि पश्यति ।': ['वाक्यम् -- कमलानि पश्यति   (  1/ 9 )', 'The sentence is in ACTIVE VOICE', '',
                                'Noun(s)', 'Subject(s) : कमलानि  (  नपुंसकलिङ्गः / प्रथमाविभक्तिः /  बहुवचनम् )',
                                'Krdanta(s)  : पश्यति ( पुल्लिङ्गः / षष्ठीविभक्तिः / बहुवचनम् )\n',
                                'The subject does not agree with the krdanta in vibhakti, vacana & linga\n The sentence is syntactically not compatible',
                                '---------------', 'वाक्यम् -- कमलानि पश्यति   (  2/ 9 )',
                                'The sentence is in ACTIVE VOICE', '', 'Noun(s)',
                                'Subject(s) : कमलानि  (  नपुंसकलिङ्गः / प्रथमाविभक्तिः /  बहुवचनम् )',
                                'Krdanta(s)  : पश्यति ( नपुंसकलिङ्गः / षष्ठीविभक्तिः / बहुवचनम् )\n',
                                'The subject agrees with the krdanta in linga only\n The sentence is syntactically not compatible',
                                '---------------', 'वाक्यम् -- कमलानि पश्यति   (  3/ 9 )',
                                'The sentence is in ACTIVE VOICE', '', 'Verb is Akarmaka(intransitive)', 'Noun(s)',
                                'Subject(s) : कमलानि  (  नपुंसकलिङ्गः / प्रथमाविभक्तिः /  बहुवचनम् )',
                                'Verb : पश्यति ( दृशिर् / प्रथमपुरुषः / द्विवचनम् )',
                                '\nThe subject agrees with the verb in purusha and vacana\n The sentence is syntactically compatible',
                                '---------------', 'वाक्यम् -- कमलानि पश्यति   (  4/ 9 )',
                                'The sentence is in ACTIVE VOICE', '', 'Noun(s)',
                                'Object(s) : कमलानि  (  नपुंसकलिङ्गः / द्वितीयाविभक्तिः /  बहुवचनम् )',
                                'Krdanta(s)  : पश्यति ( पुल्लिङ्गः / षष्ठीविभक्तिः / बहुवचनम् )\n',
                                'No matching subject is available',
                                'The adjective has a matching noun in all aspects The sentence is syntactically compatible',
                                '---------------', 'वाक्यम् -- कमलानि पश्यति   (  5/ 9 )',
                                'The sentence is in ACTIVE VOICE', '', 'Noun(s)',
                                'Object(s) : कमलानि  (  नपुंसकलिङ्गः / द्वितीयाविभक्तिः /  बहुवचनम् )',
                                'Krdanta(s)  : पश्यति ( नपुंसकलिङ्गः / षष्ठीविभक्तिः / बहुवचनम् )\n',
                                'No matching subject is available',
                                'The adjective has a matching noun in all aspects The sentence is syntactically compatible',
                                '---------------', 'वाक्यम् -- कमलानि पश्यति   (  6/ 9 )',
                                'The sentence is in ACTIVE VOICE', '', 'Considering the verb as Akarmaka(intransitive)',
                                'Noun(s)', 'Object(s) : कमलानि  (  नपुंसकलिङ्गः / द्वितीयाविभक्तिः /  बहुवचनम् )',
                                'Verb : पश्यति ( दृशिर् / प्रथमपुरुषः / द्विवचनम् )',
                                '\nअहम् can be assumed to be the subject\nThe sentence is syntactically compatible',
                                '---------------', 'वाक्यम् -- कमलानि पश्यति   (  7/ 9 )',
                                'The sentence is in ACTIVE VOICE', '', 'Noun(s)',
                                'Vocative(s) हे :कमलानि  (  नपुंसकलिङ्गः / सं/प्रथमाविभक्तिः /  बहुवचनम् )',
                                'Krdanta(s)  : पश्यति ( पुल्लिङ्गः / षष्ठीविभक्तिः / बहुवचनम् )\n',
                                'No matching subject is available',
                                'The adjective has a matching noun in all aspects The sentence is syntactically compatible',
                                '---------------', 'वाक्यम् -- कमलानि पश्यति   (  8/ 9 )',
                                'The sentence is in ACTIVE VOICE', '', 'Noun(s)',
                                'Vocative(s) हे :कमलानि  (  नपुंसकलिङ्गः / सं/प्रथमाविभक्तिः /  बहुवचनम् )',
                                'Krdanta(s)  : पश्यति ( नपुंसकलिङ्गः / षष्ठीविभक्तिः / बहुवचनम् )\n',
                                'No matching subject is available',
                                'The adjective has a matching noun in all aspects The sentence is syntactically compatible',
                                '---------------', 'वाक्यम् -- कमलानि पश्यति   (  9/ 9 )',
                                'The sentence is in ACTIVE VOICE', '', 'Verb is Akarmaka(intransitive)', 'Noun(s)',
                                'Vocative(s) हे :कमलानि  (  नपुंसकलिङ्गः / सं/प्रथमाविभक्तिः /  बहुवचनम् )',
                                'Verb : पश्यति ( दृशिर् / प्रथमपुरुषः / द्विवचनम् )',
                                '\nअहम् can be assumed to be the subject\nThe sentence is syntactically compatible',
                                '---------------'],
            'रामः पूजयति ।': ['वाक्यम् -- रामः पूजयति   (  1/ 12 )', 'The sentence is in ACTIVE VOICE', '', 'Noun(s)',
                              'Subject(s) : रामः  (  पुल्लिङ्गः / प्रथमाविभक्तिः /  एकवचनम् )',
                              'Krdanta(s)  : पूजयति ( पुल्लिङ्गः / षष्ठीविभक्तिः / बहुवचनम् )\n',
                              'The subject agrees with the krdanta in linga only\n The sentence is syntactically not compatible',
                              '---------------', 'वाक्यम् -- रामः पूजयति   (  2/ 12 )',
                              'The sentence is in ACTIVE VOICE', '', 'Noun(s)',
                              'Subject(s) : रामः  (  पुल्लिङ्गः / प्रथमाविभक्तिः /  एकवचनम् )',
                              'Krdanta(s)  : पूजयति ( नपुंसकलिङ्गः / षष्ठीविभक्तिः / बहुवचनम् )\n',
                              'The subject does not agree with the krdanta in vibhakti, vacana & linga\n The sentence is syntactically not compatible',
                              '---------------', 'वाक्यम् -- रामः पूजयति   (  3/ 12 )',
                              'The sentence is in ACTIVE VOICE', '', 'Noun(s)',
                              'Subject(s) : रामः  (  पुल्लिङ्गः / प्रथमाविभक्तिः /  एकवचनम् )',
                              'Krdanta(s)  : पूजयति ( पुल्लिङ्गः / षष्ठीविभक्तिः / बहुवचनम् )\n',
                              'The subject agrees with the krdanta in linga only\n The sentence is syntactically not compatible',
                              '---------------', 'वाक्यम् -- रामः पूजयति   (  4/ 12 )',
                              'The sentence is in ACTIVE VOICE', '', 'Noun(s)',
                              'Subject(s) : रामः  (  पुल्लिङ्गः / प्रथमाविभक्तिः /  एकवचनम् )',
                              'Krdanta(s)  : पूजयति ( नपुंसकलिङ्गः / षष्ठीविभक्तिः / बहुवचनम् )\n',
                              'The subject does not agree with the krdanta in vibhakti, vacana & linga\n The sentence is syntactically not compatible',
                              '---------------', 'वाक्यम् -- रामः पूजयति   (  5/ 12 )',
                              'The sentence is in ACTIVE VOICE', '', 'Verb is Akarmaka(intransitive)', 'Noun(s)',
                              'Subject(s) : रामः  (  पुल्लिङ्गः / प्रथमाविभक्तिः /  एकवचनम् )',
                              'Verb : पूजयति ( पूज् / प्रथमपुरुषः / द्विवचनम् )',
                              '\nThe subject agrees with the verb in purusha and vacana\n The sentence is syntactically compatible',
                              '---------------', 'वाक्यम् -- रामः पूजयति   (  6/ 12 )',
                              'The sentence is in ACTIVE VOICE', '', 'Verb is Akarmaka(intransitive)', 'Noun(s)',
                              'Subject(s) : रामः  (  पुल्लिङ्गः / प्रथमाविभक्तिः /  एकवचनम् )',
                              'Verb : पूजयति ( पूज् / प्रथमपुरुषः / द्विवचनम् )',
                              '\nThe subject agrees with the verb in purusha and vacana\n The sentence is syntactically compatible',
                              '---------------', 'वाक्यम् -- रामः पूजयति   (  7/ 12 )',
                              'The sentence is in ACTIVE VOICE', '', 'Verb is Akarmaka(intransitive)',
                              'Verb : रामः ( रा / उत्तमपुरुषः / एकवचनम् )',
                              '\nयूयम् can be assumed to be the subject\nThe sentence is syntactically compatible',
                              '---------------', 'वाक्यम् -- रामः पूजयति   (  8/ 12 )',
                              'The sentence is in ACTIVE VOICE', '', 'Verb is Akarmaka(intransitive)',
                              'Verb : रामः ( रा / उत्तमपुरुषः / एकवचनम् )',
                              '\nयूयम् can be assumed to be the subject\nThe sentence is syntactically compatible',
                              '---------------', 'वाक्यम् -- रामः पूजयति   (  9/ 12 )',
                              'The sentence is in ACTIVE VOICE', '', 'Verb is Akarmaka(intransitive)',
                              'Verb : रामः ( रा / उत्तमपुरुषः / एकवचनम् )',
                              '\nयूयम् can be assumed to be the subject\nThe sentence is syntactically compatible',
                              '---------------', 'वाक्यम् -- रामः पूजयति   (  10/ 12 )',
                              'The sentence is in ACTIVE VOICE', '', 'Verb is Akarmaka(intransitive)',
                              'Verb : रामः ( रा / उत्तमपुरुषः / एकवचनम् )',
                              '\nयूयम् can be assumed to be the subject\nThe sentence is syntactically compatible',
                              '---------------', 'वाक्यम् -- रामः पूजयति   (  11/ 12 )',
                              'The sentence is in ACTIVE VOICE', '', 'Verb is Akarmaka(intransitive)',
                              'Verb(s) are : रामः ( रा / उत्तमपुरुषः / एकवचनम् )\nपूजयति ( पूज् / प्रथमपुरुषः / द्विवचनम् )',
                              'The verbs do not agree in purusha and vacana', '---------------',
                              'वाक्यम् -- रामः पूजयति   (  12/ 12 )', 'The sentence is in ACTIVE VOICE', '',
                              'Verb is Akarmaka(intransitive)',
                              'Verb(s) are : रामः ( रा / उत्तमपुरुषः / एकवचनम् )\nपूजयति ( पूज् / प्रथमपुरुषः / द्विवचनम् )',
                              'The verbs do not agree in purusha and vacana', '---------------'],
            'व्याधयः नश्यन्ति ।': ['वाक्यम् -- व्याधयः नश्यन्ति   (  1/ 20 )', 'The sentence is in ACTIVE VOICE', '',
                                   'Considering krdanta as  SAKARMAKA (transitive)', 'Noun(s)',
                                   'Subject(s) : व्याधयः  (  पुल्लिङ्गः / प्रथमाविभक्तिः /  बहुवचनम् )',
                                   'Krdanta(s)  : नश्यन्ति ( स्त्रीलिङ्गः / सप्तमीविभक्तिः / बहुवचनम् )\n',
                                   'The subject does not agree with the krdanta in vibhakti, vacana & linga\n The sentence is syntactically not compatible',
                                   '---------------', 'वाक्यम् -- व्याधयः नश्यन्ति   (  2/ 20 )',
                                   'The sentence is in ACTIVE VOICE', '',
                                   'Considering krdanta as  SAKARMAKA (transitive)', 'Noun(s)',
                                   'Subject(s) : व्याधयः  (  पुल्लिङ्गः / प्रथमाविभक्तिः /  बहुवचनम् )',
                                   'Krdanta(s)  : नश्यन्ति ( नपुंसकलिङ्गः / सं/प्रथमाविभक्तिः / द्विवचनम् )\n',
                                   'The subject does not agree with the krdanta in vibhakti, vacana & linga\n The sentence is syntactically not compatible',
                                   '---------------', 'वाक्यम् -- व्याधयः नश्यन्ति   (  3/ 20 )',
                                   'The sentence is in ACTIVE VOICE', '',
                                   'Considering krdanta as  SAKARMAKA (transitive)', 'Noun(s)',
                                   'Subject(s) : व्याधयः  (  पुल्लिङ्गः / प्रथमाविभक्तिः /  बहुवचनम् )',
                                   'Krdanta(s)  : नश्यन्ति ( नपुंसकलिङ्गः / प्रथमाविभक्तिः / द्विवचनम् )\n',
                                   'The subject agrees with the krdanta in vibhakti and vacana only\n The sentence is syntactically not compatible',
                                   '---------------', 'वाक्यम् -- व्याधयः नश्यन्ति   (  4/ 20 )',
                                   'The sentence is in ACTIVE VOICE', '',
                                   'Considering krdanta as  SAKARMAKA (transitive)', 'Noun(s)',
                                   'Subject(s) : व्याधयः  (  पुल्लिङ्गः / प्रथमाविभक्तिः /  बहुवचनम् )',
                                   'Krdanta(s)  : नश्यन्ति ( नपुंसकलिङ्गः / सप्तमीविभक्तिः / द्विवचनम् )\n',
                                   'The subject does not agree with the krdanta in vibhakti, vacana & linga\n The sentence is syntactically not compatible',
                                   '---------------', 'वाक्यम् -- व्याधयः नश्यन्ति   (  5/ 20 )',
                                   'The sentence is in ACTIVE VOICE', '', 'Verb is Sakarmaka(transitive)', 'Noun(s)',
                                   'Subject(s) : व्याधयः  (  पुल्लिङ्गः / प्रथमाविभक्तिः /  बहुवचनम् )',
                                   'Verb : नश्यन्ति ( णश् / प्रथमपुरुषः / एकवचनम् )',
                                   '\nThe subject agrees with the verb in purusha and vacana\n The sentence is syntactically compatible',
                                   '---------------', 'वाक्यम् -- व्याधयः नश्यन्ति   (  6/ 20 )',
                                   'The sentence is in ACTIVE VOICE', '',
                                   'Considering krdanta as  SAKARMAKA (transitive)', 'Noun(s)',
                                   'Vocative(s) हे :व्याधयः  (  पुल्लिङ्गः / सं/प्रथमाविभक्तिः /  बहुवचनम् )',
                                   'Krdanta(s)  : नश्यन्ति ( स्त्रीलिङ्गः / सप्तमीविभक्तिः / बहुवचनम् )\n',
                                   'No matching subject is available',
                                   'The adjective has a matching noun in all aspects The sentence is syntactically compatible',
                                   '---------------', 'वाक्यम् -- व्याधयः नश्यन्ति   (  7/ 20 )',
                                   'The sentence is in ACTIVE VOICE', '',
                                   'Considering krdanta as  SAKARMAKA (transitive)', 'Noun(s)',
                                   'Vocative(s) हे :व्याधयः  (  पुल्लिङ्गः / सं/प्रथमाविभक्तिः /  बहुवचनम् )',
                                   'Krdanta(s)  : नश्यन्ति ( नपुंसकलिङ्गः / सं/प्रथमाविभक्तिः / द्विवचनम् )\n',
                                   'No matching subject is available',
                                   'The adjective has a matching noun in all aspects The sentence is syntactically compatible',
                                   '---------------', 'वाक्यम् -- व्याधयः नश्यन्ति   (  8/ 20 )',
                                   'The sentence is in ACTIVE VOICE', '',
                                   'Considering krdanta as  SAKARMAKA (transitive)', 'Noun(s)',
                                   'Vocative(s) हे :व्याधयः  (  पुल्लिङ्गः / सं/प्रथमाविभक्तिः /  बहुवचनम् )',
                                   'Krdanta(s)  : नश्यन्ति ( नपुंसकलिङ्गः / प्रथमाविभक्तिः / द्विवचनम् )\n',
                                   'Any subanta in प्रथमविभक्ति, द्विवचनम् \nand in पुल्लिङ्गः can be the subject\n',
                                   'The adjective has a matching noun in all aspects The sentence is syntactically compatible',
                                   '---------------', 'वाक्यम् -- व्याधयः नश्यन्ति   (  9/ 20 )',
                                   'The sentence is in ACTIVE VOICE', '',
                                   'Considering krdanta as  SAKARMAKA (transitive)', 'Noun(s)',
                                   'Vocative(s) हे :व्याधयः  (  पुल्लिङ्गः / सं/प्रथमाविभक्तिः /  बहुवचनम् )',
                                   'Krdanta(s)  : नश्यन्ति ( नपुंसकलिङ्गः / सप्तमीविभक्तिः / द्विवचनम् )\n',
                                   'No matching subject is available',
                                   'The adjective has a matching noun in all aspects The sentence is syntactically compatible',
                                   '---------------', 'वाक्यम् -- व्याधयः नश्यन्ति   (  10/ 20 )',
                                   'The sentence is in ACTIVE VOICE', '', 'Verb is Sakarmaka(transitive)', 'Noun(s)',
                                   'Vocative(s) हे :व्याधयः  (  पुल्लिङ्गः / सं/प्रथमाविभक्तिः /  बहुवचनम् )',
                                   'Verb : नश्यन्ति ( णश् / प्रथमपुरुषः / एकवचनम् )',
                                   '\nवयम् can be assumed to be the subject\nThe sentence is syntactically compatible',
                                   '---------------', 'वाक्यम् -- व्याधयः नश्यन्ति   (  11/ 20 )',
                                   'The sentence is in ACTIVE VOICE', '',
                                   'Considering krdanta as  SAKARMAKA (transitive)', 'Noun(s)',
                                   'Subject(s) : व्याधयः  (  स्त्रीलिङ्गः / प्रथमाविभक्तिः /  बहुवचनम् )',
                                   'Krdanta(s)  : नश्यन्ति ( स्त्रीलिङ्गः / सप्तमीविभक्तिः / बहुवचनम् )\n',
                                   'The subject agrees with the krdanta in linga only\n The sentence is syntactically not compatible',
                                   '---------------', 'वाक्यम् -- व्याधयः नश्यन्ति   (  12/ 20 )',
                                   'The sentence is in ACTIVE VOICE', '',
                                   'Considering krdanta as  SAKARMAKA (transitive)', 'Noun(s)',
                                   'Subject(s) : व्याधयः  (  स्त्रीलिङ्गः / प्रथमाविभक्तिः /  बहुवचनम् )',
                                   'Krdanta(s)  : नश्यन्ति ( नपुंसकलिङ्गः / सं/प्रथमाविभक्तिः / द्विवचनम् )\n',
                                   'The subject does not agree with the krdanta in vibhakti, vacana & linga\n The sentence is syntactically not compatible',
                                   '---------------', 'वाक्यम् -- व्याधयः नश्यन्ति   (  13/ 20 )',
                                   'The sentence is in ACTIVE VOICE', '',
                                   'Considering krdanta as  SAKARMAKA (transitive)', 'Noun(s)',
                                   'Subject(s) : व्याधयः  (  स्त्रीलिङ्गः / प्रथमाविभक्तिः /  बहुवचनम् )',
                                   'Krdanta(s)  : नश्यन्ति ( नपुंसकलिङ्गः / प्रथमाविभक्तिः / द्विवचनम् )\n',
                                   'The subject agrees with the krdanta in vibhakti and vacana only\n The sentence is syntactically not compatible',
                                   '---------------', 'वाक्यम् -- व्याधयः नश्यन्ति   (  14/ 20 )',
                                   'The sentence is in ACTIVE VOICE', '',
                                   'Considering krdanta as  SAKARMAKA (transitive)', 'Noun(s)',
                                   'Subject(s) : व्याधयः  (  स्त्रीलिङ्गः / प्रथमाविभक्तिः /  बहुवचनम् )',
                                   'Krdanta(s)  : नश्यन्ति ( नपुंसकलिङ्गः / सप्तमीविभक्तिः / द्विवचनम् )\n',
                                   'The subject does not agree with the krdanta in vibhakti, vacana & linga\n The sentence is syntactically not compatible',
                                   '---------------', 'वाक्यम् -- व्याधयः नश्यन्ति   (  15/ 20 )',
                                   'The sentence is in ACTIVE VOICE', '', 'Verb is Sakarmaka(transitive)', 'Noun(s)',
                                   'Subject(s) : व्याधयः  (  स्त्रीलिङ्गः / प्रथमाविभक्तिः /  बहुवचनम् )',
                                   'Verb : नश्यन्ति ( णश् / प्रथमपुरुषः / एकवचनम् )',
                                   '\nThe subject agrees with the verb in purusha and vacana\n The sentence is syntactically compatible',
                                   '---------------', 'वाक्यम् -- व्याधयः नश्यन्ति   (  16/ 20 )',
                                   'The sentence is in ACTIVE VOICE', '',
                                   'Considering krdanta as  SAKARMAKA (transitive)', 'Noun(s)',
                                   'Vocative(s) हे :व्याधयः  (  स्त्रीलिङ्गः / सं/प्रथमाविभक्तिः /  बहुवचनम् )',
                                   'Krdanta(s)  : नश्यन्ति ( स्त्रीलिङ्गः / सप्तमीविभक्तिः / बहुवचनम् )\n',
                                   'No matching subject is available',
                                   'The adjective has a matching noun in all aspects The sentence is syntactically compatible',
                                   '---------------', 'वाक्यम् -- व्याधयः नश्यन्ति   (  17/ 20 )',
                                   'The sentence is in ACTIVE VOICE', '',
                                   'Considering krdanta as  SAKARMAKA (transitive)', 'Noun(s)',
                                   'Vocative(s) हे :व्याधयः  (  स्त्रीलिङ्गः / सं/प्रथमाविभक्तिः /  बहुवचनम् )',
                                   'Krdanta(s)  : नश्यन्ति ( नपुंसकलिङ्गः / सं/प्रथमाविभक्तिः / द्विवचनम् )\n',
                                   'No matching subject is available',
                                   'The adjective has a matching noun in all aspects The sentence is syntactically compatible',
                                   '---------------', 'वाक्यम् -- व्याधयः नश्यन्ति   (  18/ 20 )',
                                   'The sentence is in ACTIVE VOICE', '',
                                   'Considering krdanta as  SAKARMAKA (transitive)', 'Noun(s)',
                                   'Vocative(s) हे :व्याधयः  (  स्त्रीलिङ्गः / सं/प्रथमाविभक्तिः /  बहुवचनम् )',
                                   'Krdanta(s)  : नश्यन्ति ( नपुंसकलिङ्गः / प्रथमाविभक्तिः / द्विवचनम् )\n',
                                   'Any subanta in प्रथमविभक्ति, द्विवचनम् \nand in पुल्लिङ्गः can be the subject\n',
                                   'The adjective has a matching noun in all aspects The sentence is syntactically compatible',
                                   '---------------', 'वाक्यम् -- व्याधयः नश्यन्ति   (  19/ 20 )',
                                   'The sentence is in ACTIVE VOICE', '',
                                   'Considering krdanta as  SAKARMAKA (transitive)', 'Noun(s)',
                                   'Vocative(s) हे :व्याधयः  (  स्त्रीलिङ्गः / सं/प्रथमाविभक्तिः /  बहुवचनम् )',
                                   'Krdanta(s)  : नश्यन्ति ( नपुंसकलिङ्गः / सप्तमीविभक्तिः / द्विवचनम् )\n',
                                   'No matching subject is available',
                                   'The adjective has a matching noun in all aspects The sentence is syntactically compatible',
                                   '---------------', 'वाक्यम् -- व्याधयः नश्यन्ति   (  20/ 20 )',
                                   'The sentence is in ACTIVE VOICE', '', 'Verb is Sakarmaka(transitive)', 'Noun(s)',
                                   'Vocative(s) हे :व्याधयः  (  स्त्रीलिङ्गः / सं/प्रथमाविभक्तिः /  बहुवचनम् )',
                                   'Verb : नश्यन्ति ( णश् / प्रथमपुरुषः / एकवचनम् )',
                                   '\nवयम् can be assumed to be the subject\nThe sentence is syntactically compatible',
                                   '---------------'],
            'अरिः पीडयति': ['वाक्यम् -- अरिः पीडयत  (  1/ 6 )', 'The sentence is in ACTIVE VOICE', '', 'Noun(s)',
                            'Subject(s) : अरिः  (  पुल्लिङ्गः / प्रथमाविभक्तिः /  एकवचनम् )',
                            'Krdanta(s)  : पीडयति ( पुल्लिङ्गः / षष्ठीविभक्तिः / बहुवचनम् )\n',
                            'The subject agrees with the krdanta in linga only\n The sentence is syntactically not compatible',
                            '---------------', 'वाक्यम् -- अरिः पीडयत  (  2/ 6 )', 'The sentence is in ACTIVE VOICE',
                            '', 'Noun(s)', 'Subject(s) : अरिः  (  पुल्लिङ्गः / प्रथमाविभक्तिः /  एकवचनम् )',
                            'Krdanta(s)  : पीडयति ( नपुंसकलिङ्गः / षष्ठीविभक्तिः / बहुवचनम् )\n',
                            'The subject does not agree with the krdanta in vibhakti, vacana & linga\n The sentence is syntactically not compatible',
                            '---------------', 'वाक्यम् -- अरिः पीडयत  (  3/ 6 )', 'The sentence is in ACTIVE VOICE',
                            '', 'Noun(s)', 'Subject(s) : अरिः  (  पुल्लिङ्गः / प्रथमाविभक्तिः /  एकवचनम् )',
                            'Krdanta(s)  : पीडयति ( पुल्लिङ्गः / षष्ठीविभक्तिः / बहुवचनम् )\n',
                            'The subject agrees with the krdanta in linga only\n The sentence is syntactically not compatible',
                            '---------------', 'वाक्यम् -- अरिः पीडयत  (  4/ 6 )', 'The sentence is in ACTIVE VOICE',
                            '', 'Noun(s)', 'Subject(s) : अरिः  (  पुल्लिङ्गः / प्रथमाविभक्तिः /  एकवचनम् )',
                            'Krdanta(s)  : पीडयति ( नपुंसकलिङ्गः / षष्ठीविभक्तिः / बहुवचनम् )\n',
                            'The subject does not agree with the krdanta in vibhakti, vacana & linga\n The sentence is syntactically not compatible',
                            '---------------', 'वाक्यम् -- अरिः पीडयत  (  5/ 6 )', 'The sentence is in ACTIVE VOICE',
                            '', 'Verb is Akarmaka(intransitive)', 'Noun(s)',
                            'Subject(s) : अरिः  (  पुल्लिङ्गः / प्रथमाविभक्तिः /  एकवचनम् )',
                            'Verb : पीडयति ( पीड् / प्रथमपुरुषः / द्विवचनम् )',
                            '\nThe subject agrees with the verb in purusha and vacana\n The sentence is syntactically compatible',
                            '---------------', 'वाक्यम् -- अरिः पीडयत  (  6/ 6 )', 'The sentence is in ACTIVE VOICE',
                            '', 'Verb is Akarmaka(intransitive)', 'Noun(s)',
                            'Subject(s) : अरिः  (  पुल्लिङ्गः / प्रथमाविभक्तिः /  एकवचनम् )',
                            'Verb : पीडयति ( पीड् / प्रथमपुरुषः / द्विवचनम् )',
                            '\nThe subject agrees with the verb in purusha and vacana\n The sentence is syntactically compatible',
                            '---------------'],
            'नृपः जयति ।': ['वाक्यम् -- नृपः जयति   (  1/ 3 )', 'The sentence is in ACTIVE VOICE', '', 'Noun(s)',
                            'Subject(s) : नृपः  (  पुल्लिङ्गः / प्रथमाविभक्तिः /  एकवचनम् )',
                            'Krdanta(s)  : जयति ( पुल्लिङ्गः / षष्ठीविभक्तिः / बहुवचनम् )\n',
                            'The subject agrees with the krdanta in linga only\n The sentence is syntactically not compatible',
                            '---------------', 'वाक्यम् -- नृपः जयति   (  2/ 3 )', 'The sentence is in ACTIVE VOICE',
                            '', 'Noun(s)', 'Subject(s) : नृपः  (  पुल्लिङ्गः / प्रथमाविभक्तिः /  एकवचनम् )',
                            'Krdanta(s)  : जयति ( नपुंसकलिङ्गः / षष्ठीविभक्तिः / बहुवचनम् )\n',
                            'The subject does not agree with the krdanta in vibhakti, vacana & linga\n The sentence is syntactically not compatible',
                            '---------------', 'वाक्यम् -- नृपः जयति   (  3/ 3 )', 'The sentence is in ACTIVE VOICE',
                            '', 'Verb is Akarmaka(intransitive)', 'Noun(s)',
                            'Subject(s) : नृपः  (  पुल्लिङ्गः / प्रथमाविभक्तिः /  एकवचनम् )',
                            'Verb : जयति ( जि / प्रथमपुरुषः / द्विवचनम् )',
                            '\nThe subject agrees with the verb in purusha and vacana\n The sentence is syntactically compatible',
                            '---------------'],
            'धनं नश्यति ।': ['वाक्यम् -- धनं नश्यति   (  1/ 6 )', 'The sentence is in ACTIVE VOICE', '',
                             'Considering krdanta as  SAKARMAKA (transitive)', 'Noun(s)',
                             'Subject(s) : धनं  (  नपुंसकलिङ्गः / प्रथमाविभक्तिः /  एकवचनम् )',
                             'Krdanta(s)  : नश्यति ( पुल्लिङ्गः / षष्ठीविभक्तिः / बहुवचनम् )\n',
                             'The subject does not agree with the krdanta in vibhakti, vacana & linga\n The sentence is syntactically not compatible',
                             '---------------', 'वाक्यम् -- धनं नश्यति   (  2/ 6 )', 'The sentence is in ACTIVE VOICE',
                             '', 'Considering krdanta as  SAKARMAKA (transitive)', 'Noun(s)',
                             'Subject(s) : धनं  (  नपुंसकलिङ्गः / प्रथमाविभक्तिः /  एकवचनम् )',
                             'Krdanta(s)  : नश्यति ( नपुंसकलिङ्गः / षष्ठीविभक्तिः / बहुवचनम् )\n',
                             'The subject agrees with the krdanta in linga only\n The sentence is syntactically not compatible',
                             '---------------', 'वाक्यम् -- धनं नश्यति   (  3/ 6 )', 'The sentence is in ACTIVE VOICE',
                             '', 'Verb is Sakarmaka(transitive)', 'Noun(s)',
                             'Subject(s) : धनं  (  नपुंसकलिङ्गः / प्रथमाविभक्तिः /  एकवचनम् )',
                             'Verb : नश्यति ( णश् / प्रथमपुरुषः / द्विवचनम् )',
                             '\nThe subject agrees with the verb in purusha and vacana\n The sentence is syntactically compatible',
                             '---------------', 'वाक्यम् -- धनं नश्यति   (  4/ 6 )', 'The sentence is in ACTIVE VOICE',
                             '', 'Noun(s)', 'Object(s) : धनं  (  नपुंसकलिङ्गः / द्वितीयाविभक्तिः /  एकवचनम् )',
                             'Krdanta(s)  : नश्यति ( पुल्लिङ्गः / षष्ठीविभक्तिः / बहुवचनम् )\n',
                             'No matching subject is available',
                             'The adjective has a matching noun in all aspects The sentence is syntactically compatible',
                             '---------------', 'वाक्यम् -- धनं नश्यति   (  5/ 6 )', 'The sentence is in ACTIVE VOICE',
                             '', 'Noun(s)', 'Object(s) : धनं  (  नपुंसकलिङ्गः / द्वितीयाविभक्तिः /  एकवचनम् )',
                             'Krdanta(s)  : नश्यति ( नपुंसकलिङ्गः / षष्ठीविभक्तिः / बहुवचनम् )\n',
                             'No matching subject is available',
                             'The adjective has a matching noun in all aspects The sentence is syntactically compatible',
                             '---------------', 'वाक्यम् -- धनं नश्यति   (  6/ 6 )', 'The sentence is in ACTIVE VOICE',
                             '', 'Verb is Sakarmaka(transitive)', 'Noun(s)',
                             'Object(s) : धनं  (  नपुंसकलिङ्गः / द्वितीयाविभक्तिः /  एकवचनम् )',
                             'Verb : नश्यति ( णश् / प्रथमपुरुषः / द्विवचनम् )',
                             '\nअहम् can be assumed to be the subject\nThe sentence is syntactically compatible',
                             '---------------'],
            'वारीणि शुष्यन्ति ।': ['वाक्यम् -- वारीणि शुष्यन्ति   (  1/ 15 )', 'The sentence is in ACTIVE VOICE', '',
                                   'Noun(s)', 'Subject(s) : वारीणि  (  नपुंसकलिङ्गः / प्रथमाविभक्तिः /  बहुवचनम् )',
                                   'Krdanta(s)  : शुष्यन्ति ( स्त्रीलिङ्गः / सप्तमीविभक्तिः / बहुवचनम् )\n',
                                   'The subject does not agree with the krdanta in vibhakti, vacana & linga\n The sentence is syntactically not compatible',
                                   '---------------', 'वाक्यम् -- वारीणि शुष्यन्ति   (  2/ 15 )',
                                   'The sentence is in ACTIVE VOICE', '', 'Noun(s)',
                                   'Subject(s) : वारीणि  (  नपुंसकलिङ्गः / प्रथमाविभक्तिः /  बहुवचनम् )',
                                   'Krdanta(s)  : शुष्यन्ति ( नपुंसकलिङ्गः / सं/प्रथमाविभक्तिः / द्विवचनम् )\n',
                                   'The subject agrees with the krdanta in linga only\n The sentence is syntactically not compatible',
                                   '---------------', 'वाक्यम् -- वारीणि शुष्यन्ति   (  3/ 15 )',
                                   'The sentence is in ACTIVE VOICE', '', 'Noun(s)',
                                   'Subject(s) : वारीणि  (  नपुंसकलिङ्गः / प्रथमाविभक्तिः /  बहुवचनम् )',
                                   'Krdanta(s)  : शुष्यन्ति ( नपुंसकलिङ्गः / प्रथमाविभक्तिः / द्विवचनम् )\n',
                                   'The subject agrees with the krdanta in vibhakti, vacana and linga\n The sentence is syntactically compatible',
                                   '---------------', 'वाक्यम् -- वारीणि शुष्यन्ति   (  4/ 15 )',
                                   'The sentence is in ACTIVE VOICE', '', 'Noun(s)',
                                   'Subject(s) : वारीणि  (  नपुंसकलिङ्गः / प्रथमाविभक्तिः /  बहुवचनम् )',
                                   'Krdanta(s)  : शुष्यन्ति ( नपुंसकलिङ्गः / सप्तमीविभक्तिः / द्विवचनम् )\n',
                                   'The subject agrees with the krdanta in linga only\n The sentence is syntactically not compatible',
                                   '---------------', 'वाक्यम् -- वारीणि शुष्यन्ति   (  5/ 15 )',
                                   'The sentence is in ACTIVE VOICE', '', 'Verb is Akarmaka(intransitive)', 'Noun(s)',
                                   'Subject(s) : वारीणि  (  नपुंसकलिङ्गः / प्रथमाविभक्तिः /  बहुवचनम् )',
                                   'Verb : शुष्यन्ति ( शुष् / प्रथमपुरुषः / एकवचनम् )',
                                   '\nThe subject agrees with the verb in purusha and vacana\n The sentence is syntactically compatible',
                                   '---------------', 'वाक्यम् -- वारीणि शुष्यन्ति   (  6/ 15 )',
                                   'The sentence is in ACTIVE VOICE', '', 'Noun(s)',
                                   'Object(s) : वारीणि  (  नपुंसकलिङ्गः / द्वितीयाविभक्तिः /  बहुवचनम् )',
                                   'Krdanta(s)  : शुष्यन्ति ( स्त्रीलिङ्गः / सप्तमीविभक्तिः / बहुवचनम् )\n',
                                   'No matching subject is available',
                                   'The adjective has a matching noun in all aspects The sentence is syntactically compatible',
                                   '---------------', 'वाक्यम् -- वारीणि शुष्यन्ति   (  7/ 15 )',
                                   'The sentence is in ACTIVE VOICE', '', 'Noun(s)',
                                   'Object(s) : वारीणि  (  नपुंसकलिङ्गः / द्वितीयाविभक्तिः /  बहुवचनम् )',
                                   'Krdanta(s)  : शुष्यन्ति ( नपुंसकलिङ्गः / सं/प्रथमाविभक्तिः / द्विवचनम् )\n',
                                   'No matching subject is available',
                                   'The adjective has a matching noun in all aspects The sentence is syntactically compatible',
                                   '---------------', 'वाक्यम् -- वारीणि शुष्यन्ति   (  8/ 15 )',
                                   'The sentence is in ACTIVE VOICE', '', 'Noun(s)',
                                   'Object(s) : वारीणि  (  नपुंसकलिङ्गः / द्वितीयाविभक्तिः /  बहुवचनम् )',
                                   'Krdanta(s)  : शुष्यन्ति ( नपुंसकलिङ्गः / प्रथमाविभक्तिः / द्विवचनम् )\n',
                                   'Any subanta in प्रथमविभक्ति, द्विवचनम् \nand in पुल्लिङ्गः can be the subject\n',
                                   'The adjective has a matching noun in all aspects The sentence is syntactically compatible',
                                   '---------------', 'वाक्यम् -- वारीणि शुष्यन्ति   (  9/ 15 )',
                                   'The sentence is in ACTIVE VOICE', '', 'Noun(s)',
                                   'Object(s) : वारीणि  (  नपुंसकलिङ्गः / द्वितीयाविभक्तिः /  बहुवचनम् )',
                                   'Krdanta(s)  : शुष्यन्ति ( नपुंसकलिङ्गः / सप्तमीविभक्तिः / द्विवचनम् )\n',
                                   'No matching subject is available',
                                   'The adjective has a matching noun in all aspects The sentence is syntactically compatible',
                                   '---------------', 'वाक्यम् -- वारीणि शुष्यन्ति   (  10/ 15 )',
                                   'The sentence is in ACTIVE VOICE', '',
                                   'Considering the verb as Akarmaka(intransitive)', 'Noun(s)',
                                   'Object(s) : वारीणि  (  नपुंसकलिङ्गः / द्वितीयाविभक्तिः /  बहुवचनम् )',
                                   'Verb : शुष्यन्ति ( शुष् / प्रथमपुरुषः / एकवचनम् )',
                                   '\nवयम् can be assumed to be the subject\nThe sentence is syntactically compatible',
                                   '---------------', 'वाक्यम् -- वारीणि शुष्यन्ति   (  11/ 15 )',
                                   'The sentence is in ACTIVE VOICE', '', 'Noun(s)',
                                   'Vocative(s) हे :वारीणि  (  नपुंसकलिङ्गः / सं/प्रथमाविभक्तिः /  बहुवचनम् )',
                                   'Krdanta(s)  : शुष्यन्ति ( स्त्रीलिङ्गः / सप्तमीविभक्तिः / बहुवचनम् )\n',
                                   'No matching subject is available',
                                   'The adjective has a matching noun in all aspects The sentence is syntactically compatible',
                                   '---------------', 'वाक्यम् -- वारीणि शुष्यन्ति   (  12/ 15 )',
                                   'The sentence is in ACTIVE VOICE', '', 'Noun(s)',
                                   'Vocative(s) हे :वारीणि  (  नपुंसकलिङ्गः / सं/प्रथमाविभक्तिः /  बहुवचनम् )',
                                   'Krdanta(s)  : शुष्यन्ति ( नपुंसकलिङ्गः / सं/प्रथमाविभक्तिः / द्विवचनम् )\n',
                                   'No matching subject is available',
                                   'The adjective has a matching noun in all aspects The sentence is syntactically compatible',
                                   '---------------', 'वाक्यम् -- वारीणि शुष्यन्ति   (  13/ 15 )',
                                   'The sentence is in ACTIVE VOICE', '', 'Noun(s)',
                                   'Vocative(s) हे :वारीणि  (  नपुंसकलिङ्गः / सं/प्रथमाविभक्तिः /  बहुवचनम् )',
                                   'Krdanta(s)  : शुष्यन्ति ( नपुंसकलिङ्गः / प्रथमाविभक्तिः / द्विवचनम् )\n',
                                   'Any subanta in प्रथमविभक्ति, द्विवचनम् \nand in पुल्लिङ्गः can be the subject\n',
                                   'The adjective has a matching noun in all aspects The sentence is syntactically compatible',
                                   '---------------', 'वाक्यम् -- वारीणि शुष्यन्ति   (  14/ 15 )',
                                   'The sentence is in ACTIVE VOICE', '', 'Noun(s)',
                                   'Vocative(s) हे :वारीणि  (  नपुंसकलिङ्गः / सं/प्रथमाविभक्तिः /  बहुवचनम् )',
                                   'Krdanta(s)  : शुष्यन्ति ( नपुंसकलिङ्गः / सप्तमीविभक्तिः / द्विवचनम् )\n',
                                   'No matching subject is available',
                                   'The adjective has a matching noun in all aspects The sentence is syntactically compatible',
                                   '---------------', 'वाक्यम् -- वारीणि शुष्यन्ति   (  15/ 15 )',
                                   'The sentence is in ACTIVE VOICE', '', 'Verb is Akarmaka(intransitive)', 'Noun(s)',
                                   'Vocative(s) हे :वारीणि  (  नपुंसकलिङ्गः / सं/प्रथमाविभक्तिः /  बहुवचनम् )',
                                   'Verb : शुष्यन्ति ( शुष् / प्रथमपुरुषः / एकवचनम् )',
                                   '\nवयम् can be assumed to be the subject\nThe sentence is syntactically compatible',
                                   '---------------'],
            'नाविकाः नदेन समुद्रं प्रविशन्ति  ।': ['वाक्यम् -- नाविकाः नदेन समुद्रं प्रविशन्ति    (  1/ 2 )',
                                                   'वाक्यम् -- नाविकाः नदेन समुद्रं प्रविशन्ति    (  1/ 2 )',
                                                   'Noun(s) are:', 'नाविकाः, ', 'नदेन, ', 'समुद्रं, ',
                                                   'वाक्यम् -- नाविकाः नदेन समुद्रं प्रविशन्ति    (  2/ 2 )',
                                                   'वाक्यम् -- नाविकाः नदेन समुद्रं प्रविशन्ति    (  2/ 2 )',
                                                   'Noun(s) are:', 'नाविकाः, ', 'नदेन, ', 'समुद्रं, ']}

        syntaxInputFile = []
        for i, word in enumerate(sentence.split(' ')):
            word = AmaraKosha_Database_Queries.unicode_iscii(word)
            try:
                wids = 1
                forms, subDetails = Kosha_Subanta_Krdanta_Tiganta.subanta_Analysis(word)
                if not forms == []: subforms += forms
                for item in subDetails:
                    numpages += 1
                    Subantas.append([item.rupam,
                                     transliterate_lines(AmaraKosha_Database_Queries.iscii_unicode(item.base),
                                                         IndianLanguages[0]),
                                     item.anta, item.linga, item.vib, item.vach, item.vibvach])
                    syntaxInputFile.append([i + 1, word, wids, 1, item.base, item.erb, item.det, item.vibvach + 1])
                    wids += 1
            except Exception as e:
                print(e)
            try:
                forms, krdData = Kosha_Subanta_Krdanta_Tiganta.krdanta_Analysis(word)
                if not forms == []: krdforms += forms
                if not krdData == []:
                    Krdantas += krdData
                    numpages += len(krdData)
                    for krdDetail in krdData:
                        syntaxInputFile.append(
                            [i + 1, word, wids, 2, krdDetail.erb_iscii, krdDetail.sabda_iscii, krdDetail.det,
                             krdDetail.vibvach + 1, krdDetail.ddet, krdDetail.Dno, krdDetail.verb_iscii,
                             krdDetail.nijverb_iscii,
                             krdDetail.sanverb_iscii, krdDetail.meaning_iscii, krdDetail.GPICode,
                             krdDetail.CombinedM,
                             krdDetail.karmaCode])
                        wids += 1
            except Exception as e:
                print(e)
            try:
                forms, tigDatas = Kosha_Subanta_Krdanta_Tiganta.tiganta_Analysis(word)
                if not forms == []: tigforms += forms
                if not tigDatas == []:
                    Tigantas += tigDatas
                    numpages += len(tigDatas)
                    for tigData in tigDatas:
                        # ic.ic('tiganta', i+1, word, wids)
                        syntaxInputFile.append(
                            [i + 1, word, wids, 5, tigData.base_iscii, tigData.Dno, tigData.verb_iscii,
                             tigData.nijverb_iscii, tigData.sanverb_iscii, tigData.meaning_iscii, tigData.GPICode,
                             tigData.pralak, tigData.purvach, tigData.CombinedM, tigData.karmaCode])
                        wids += 1
            except Exception as e:
                print(e)
        # ic.ic(numpages, subforms, krdforms, tigforms, Subantas, [item.get() for item in Krdantas], [item.get() for item in Tigantas], syntaxInputFile)

        morphologicalOutput = [AmaraKosha_Database_Queries.unicode_iscii('वाक्यम्') + ' -- %s' % AmaraKosha_Database_Queries.unicode_iscii(sentence)]
        for line in syntaxInputFile:
            morphologicalOutput.append('%d) ' % line[0] + ' '.join([str(x) for x in line[1:]]))
        morphologicalOutput.append('----------')
        try:
            out = SyntaxAnalysis.write_out_aci(morphologicalOutput)
            result = SyntaxAnalysis.write_result_aci(out)
            self.assertEqual(outExpected[sentence], [AmaraKosha_Database_Queries.iscii_unicode(l) for l in out])
            self.assertEqual(resultExpected[sentence], [AmaraKosha_Database_Queries.iscii_unicode(l) for l in result])
        except Exception as e:
            ic.ic(sentence, e)